### ISSUE TITLE
Psychotic draft

### ISSUE THREAD

**Issue by lucsou-dev** [UnlimitedHugs/RimworldDefensivePositions#2]
I have a pawn (Dragonfly) in _psychotic wandering_ and, even though it should be impossible, when I pressed "0" it went to the first defensive position (she is in advanced mode).

![crazy_dragonfly](https://cloud.githubusercontent.com/assets/19523324/19752166/058899b6-9bda-11e6-8102-24614518661c.png)

**Comment by lucsou-dev** [comment]
Just noticed that I don't have any _interface_ with her, even though she went to her defensive position when I pressed "0".

![crazy_dragonfly_2](https://cloud.githubusercontent.com/assets/19523324/19752239/9a30e028-9bda-11e6-94f6-895ba08906a1.png)

When I pressed "/" she, and every other pawn, went back to normal.

**Comment by UnlimitedHugs** [comment]
Good catch, thank you. Fixed now.
